# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.aliases = {'q': 'quit', 'w': 'session-save', 'wq': 'quit --save'}

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Permissions
config.set('content.register_protocol_handler', True, '*://mail.google.com/*')
config.set('content.register_protocol_handler', True, '*://calendar.google.com/*')

# Pop-up Windows
config.set('content.javascript.can_open_tabs_automatically', True)

c.zoom.default = "90%"

# Color gradient interpolation system for download text.
# Type: ColorSystem
# Valid values:
#   - rgb: Interpolate in the RGB color system.
#   - hsv: Interpolate in the HSV color system.
#   - hsl: Interpolate in the HSL color system.
#   - none: Don't show a gradient.
c.colors.downloads.system.fg = 'rgb'

# Font color for hints.
# Type: QssColor
c.colors.hints.fg = '#2d2d2d'
c.colors.hints.match.fg = '#99cc99'
c.colors.hints.bg = 'rgba(255, 204, 102, 80%)'


# Colors for Completion
c.colors.completion.even.bg = '#66cccc'
c.colors.completion.odd.bg = '#5bb7b7'
c.colors.completion.fg = '#2d2d2d'

c.colors.completion.match.fg ='#f2777a'
c.colors.completion.item.selected.bg ='#ffcc66'

c.colors.completion.category.bg = '#2d2d2d'

c.colors.statusbar.insert.bg = '#99cc99'
c.colors.statusbar.insert.fg = '#2d2d2d'

# Colors for Tabs
c.colors.tabs.even.bg = '#99cc99'
c.colors.tabs.odd.bg = '#7aa37a'
c.colors.tabs.even.fg = '#2d2d2d'
c.colors.tabs.odd.fg = '#2d2d2d'

c.colors.tabs.selected.even.bg = '#2d2d2d'
c.colors.tabs.selected.odd.bg = '#2d2d2d'
c.colors.tabs.selected.even.fg = '#99cc99'
c.colors.tabs.selected.odd.fg = '#99cc99'

# Colors for Statusbar
c.colors.statusbar.command.bg = '#2d2d2d'
c.colors.statusbar.command.fg = '#99cc99'
c.colors.statusbar.normal.bg = '#2d2d2d'
c.colors.statusbar.normal.fg = '#99cc99'

# Colors for Statusbar URLs
c.colors.statusbar.url.success.https.fg = '#99cc99'
c.colors.statusbar.url.error.fg = '#f99157'

# Colors for download bar
c.colors.downloads.bar.bg = '#2d2d2d'
c.colors.downloads.error.bg = '#f2777a'
c.colors.downloads.error.fg = '#2d2d2d'
c.colors.downloads.stop.bg = '#cc99cc'
c.colors.downloads.stop.fg = '#2d2d2d'

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = '"DejaVu Sans Mono", "xos4 Terminus", Terminus, Monospace, Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", monospace, Fixed, Consolas, Terminal'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '10pt monospace'
c.fonts.tabs = '12pt Roboto Condensed'
c.fonts.statusbar = '12pt Roboto Condensed'
